penjual/controllers/DiskonController.php
<?php

namespace penjual\controllers;

use common\models\Diskon;
use common\models\Produk;
use penjual\models\DiskonSearch;
use Yii;
use yii\bootstrap4\ActiveForm;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;


/**
 * DiskonController implements the CRUD actions for Diskon model.
 */
class DiskonController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    ['actions' => ['index', 'create', 'update', 'view', 'delete'],
                        'allow' => true,
                        'roles' => ['@']
                    ]
                ]
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Diskon models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new DiskonSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Diskon model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Finds the Diskon model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Diskon the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Diskon::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /**
     * Creates a new Diskon model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Diskon();
        $dataProduk = $this->getProduk();

        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }
        if ($model->load(Yii::$app->request->post())) {


            $model->save();
            Yii::$app->session->setFlash('success', 'Berhasil menambahkan Diskon.');

            return $this->redirect(['view', 'id' => $model->id]);
        } elseif (Yii::$app->request->isAjax) {
            return $this->renderAjax('_form', ['model' => $model, 'dataProduk' => $dataProduk]);
        }

        return $this->render('create', [
            'model' => $model,
            'dataProduk' => $dataProduk
        ]);
    }

    private function getProduk()
    {
        return ArrayHelper::map(Produk::find()->where(['id_booth' => Yii::$app->user->identity->booth->id])->all(), 'id', 'nama');
    }

    /**
     * Updates an existing Diskon model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $dataProduk = $this->getProduk();

        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Berhasil mengubah Diskon.');

            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
            'dataProduk' => $dataProduk
        ]);
    }

    /**
     * Deletes an existing Diskon model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        Yii::$app->session->setFlash('success', 'Berhasil menghapus Diskon.');

        return $this->redirect(['index']);
    }
}

penjual/controllers/PromoController.php
<?php

namespace penjual\controllers;

use common\models\Model;
use common\models\Promo;
use common\models\PromoProduk;
use penjual\models\PromoSearch;
use Yii;
use yii\bootstrap4\ActiveForm;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;


/**
 * PromoController implements the CRUD actions for Promo model.
 */
class PromoController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    ['actions' => ['index', 'create', 'update', 'view', 'delete'],
                        'allow' => true,
                        'roles' => ['@']
                    ]
                ]
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Promo models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PromoSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Promo model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Finds the Promo model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Promo the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Promo::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /**
     * Creates a new Promo model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
//        $model = new Promo();
//
//        if(Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())){
//            Yii::$app->response->format = Response::FORMAT_JSON;
//            return ActiveForm::validate($model);
//        }
//        if ($model->load(Yii::$app->request->post())) {
//
//
//            $model->save();
//            Yii::$app->session->setFlash('success','Berhasil menambahkan Promo.');
//
//            return $this->redirect(['view', 'id' => $model->id]);
//        }
//
//        elseif (Yii::$app->request->isAjax){
//            return $this->renderAjax('_form',['model'=>$model]);
//        }
//
//        return $this->render('create', [
//            'model' => $model,
//        ]);

        $modelPromo = new Promo();
        $modelPromo->id_booth = Yii::$app->user->identity->booth->id;
        $modelsProduk = [new PromoProduk()];
        if ($modelPromo->load(Yii::$app->request->post())) {
            $modelsProduk = Model::createMultiple(PromoProduk::class);
            Model::loadMultiple($modelsProduk, Yii::$app->request->post());

            //ajax validation
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ArrayHelper::merge(
                    ActiveForm::validateMultiple($modelsProduk),
                    ActiveForm::validate($modelPromo)
                );
            }

            //validate all models
            $valid = $modelPromo->validate();
            $valid = Model::validateMultiple($modelsProduk) && $valid;
            if ($valid) {
                $transaction = Yii::$app->db->beginTransaction();
                try {
                    if ($flag = $modelPromo->save(false)) {
                        foreach ($modelsProduk as /** @var $promoProduk PromoProduk */ $promoProduk) {
                            $promoProduk->id_promo = $modelPromo->id;
                            if (!($flag = $promoProduk->save(false))) {
                                $transaction->rollBack();
                                break;
                            }
                        }
                    }
                    if ($flag) {
                        $transaction->commit();
                        Yii::$app->session->setFlash('success', 'Berhasil menambahkan Promo.');

                        return $this->redirect(['index']);
                    }
                } catch (\Exception $exception) {
                    $transaction->rollBack();
                }
            }
        }
        return $this->render('create', [
            'modelPromo' => $modelPromo,
            'modelsProduk' => (empty($modelsProduk)) ? [new PromoProduk()] : $modelsProduk,
            'produkList' => $this->getProduks()

        ]);
    }

    protected function getProduks()
    {
        return ArrayHelper::map(Yii::$app->user->identity->booth->produks, 'id', 'nama');
    }

    /**
     * Updates an existing Promo model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
//        $model = $this->findModel($id);
//
//        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
//            Yii::$app->response->format = Response::FORMAT_JSON;
//            return ActiveForm::validate($model);
//        }
//        if ($model->load(Yii::$app->request->post()) && $model->save()) {
//            Yii::$app->session->setFlash('success', 'Berhasil mengubah Promo.');
//
//            return $this->redirect(['view', 'id' => $model->id]);
//        }
//
//        return $this->render('update', [
//            'model' => $model,
//        ]);
        $modelPromo = $this->findModel($id);
        $modelPromo->id_booth = Yii::$app->user->identity->booth->id;
        $modelsProduk = $modelPromo->promoProduks;
        if ($modelPromo->load(Yii::$app->request->post())) {
            $oldIds = ArrayHelper::map($modelsProduk, 'id', 'id');
            $modelsProduk = Model::createMultiple(PromoProduk::class, $modelsProduk);
            Model::loadMultiple($modelsProduk, Yii::$app->request->post());
            $deletedIds = array_diff($oldIds, array_filter(ArrayHelper::map($modelsProduk, 'id', 'id')));

            //ajax validation
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ArrayHelper::merge(
                    ActiveForm::validateMultiple($modelsProduk),
                    ActiveForm::validate($modelPromo)
                );
            }
            //validate all models
            $valid = $modelPromo->validate();
            $valid = Model::validateMultiple($modelsProduk) && $valid;

            if ($valid) {
                $transaction = Yii::$app->db->beginTransaction();
                try {
                    if ($flag = $modelPromo->save(false)) {
                        if (!empty($deletedIds)) {
                            PromoProduk::deleteAll(['id' => $deletedIds]);
                        }
                        foreach ($modelsProduk as $promoProduk) {
                            $promoProduk->id_promo = $modelPromo->id;
                            if (!($flag = $promoProduk->save(false))) {
                                $transaction->rollBack();
                                break;
                            }
                        }
                    }
                    if ($flag) {
                        $transaction->commit();
                        Yii::$app->session->setFlash('success', 'Berhasil mengubah Promo.');

                        return $this->redirect(['view', 'id' => $modelPromo->id]);
                    }
                } catch (\Exception $exception) {
                    $transaction->rollBack();
                }
            }
        }
        return $this->render('update', [
            'modelPromo' => $modelPromo,
            'modelsProduk' => (empty($modelsProduk)) ? [new PromoProduk()] : $modelsProduk,
            'produkList' => $this->getProduks()
        ]);
    }

    /**
     * Deletes an existing Promo model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        Yii::$app->session->setFlash('success', 'Berhasil menghapus Promo.');

        return $this->redirect(['index']);
    }
}

penjual/views/layouts/aside.php
<?php

use common\widgets\Menu;
use mdm\admin\components\Helper;


$menuItems = [
    [
        'label' => 'Dashboard', 'icon' => "<i class='la la-dashboard'></i>", 'url' => ['/site/index']
    ],
    [
        'label' => 'Produk',
        'icon' => '<i class="la la-android"></i>',
        'url' => ['#'],
        'items' => [
            ['label' => 'Produk', 'icon' => '<i class="kt-menu__link-bullet kt-menu__link-bullet--dot"><span></span></i>', 'url' => ['/produk/index'],],
            [
                'label' => 'Promo',
                'icon' => '<i class="kt-menu__link-bullet kt-menu__link-bullet--dot"><span></span></i>',
                'url' => ['/promo/index'],
            ],
            [
                'label' => 'Diskon',
                'icon' => '<i class="kt-menu__link-bullet kt-menu__link-bullet--dot"><span></span></i>',
                'url' => ['/diskon/index'],
            ],

        ],
    ],

    ['label' => 'Permintaan', 'icon' => '<i class="la la-inbox"></i>', 'url' => ['/permintaan/index'],],
    ['label' => 'TransaksiProduk', 'icon' => '<i class="la la-money"></i>', 'url' => ['/transaksi/index'],
        'items' => [
            ['label' => 'TransaksiProduk Masuk', 'icon' => '<i class="kt-menu__link-bullet kt-menu__link-bullet--dot"><span></span></i>', 'url' => ['/transaksi/masuk'],],
            ['label' => 'Reimburse', 'icon' => '<i class="kt-menu__link-bullet kt-menu__link-bullet--dot"><span></span></i>', 'url' => ['/transaksi/reimburse'],],
        ]
    ],
    ['label' => 'Umpan Balik', 'icon' => '<i class="la la-smile-o"></i>', 'url' => ['/request/index'],],

];
$menuItems = Helper::filter($menuItems);

?>
<!-- begin:: Aside -->
<button class="kt-aside-close " id="kt_aside_close_btn"><i class="la la-close"></i></button>
<div class="kt-aside  kt-aside--fixed  kt-grid__item kt-grid kt-grid--desktop kt-grid--hor-desktop" id="kt_aside">

    <!-- begin:: Aside Menu -->
    <div class="kt-aside-menu-wrapper kt-grid__item kt-grid__item--fluid" id="kt_aside_menu_wrapper">
        <div id="kt_aside_menu" class="kt-aside-menu " data-ktmenu-vertical="1" data-ktmenu-scroll="1"
             data-ktmenu-dropdown-timeout="500">


            <?= Menu::widget(

                [
                    'options' => ['class' => 'kt-menu__nav'],
                    'items' => $menuItems,
                ]
            ) ?>
        </div>
    </div>

    <!-- end:: Aside Menu -->
</div>

<!-- end:: Aside -->

penjual/views/layouts/content.php
<?php
/**
 * Project: kriteria.
 * @author Adryan Eka Vandra <adryanekavandra@gmail.com>
 *
 * Date: 7/26/2019
 * Time: 12:54 AM
 */

/* @var $this \yii\web\View */
/* @var $content string */


?>
<!-- begin:: Content -->

<div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
    <?=$content ?>
</div>
<!-- end:: Content -->

penjual/views/layouts/footer.php
<?php

use yii\bootstrap4\Html;

?>
<!-- begin:: Footer -->
<div class="kt-footer kt-grid__item kt-grid kt-grid--desktop kt-grid--ver-desktop" id="kt_footer">
    <div class="kt-footer__copyright">
        <?= date('Y') ?>&nbsp;&copy;&nbsp;<a href="http://keenthemes.com/metronic" target="_blank" class="kt-link">
            <?= Html::encode(Yii::$app->params['instansi'])?> by Adryan Eka Vandra</a>
    </div>
    <div class="kt-footer__menu">
        <a href="https://uin-suska.ac.id" target="_blank" class="kt-footer__menu-link kt-link"><?=Yii::$app->params['instansi']?></a>
    </div>
</div>

<!-- end:: Footer -->

penjual/views/layouts/main-error.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use common\assets\metronic\MetronicErrorPageDemo6Asset;
use common\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;
use yii\helpers\Url;
use yii\widgets\Breadcrumbs;

MetronicErrorPageDemo6Asset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <!--begin::Fonts -->
    <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.16/webfont.js"></script>
    <script>
        WebFont.load({
            google: {
                "families": ["Poppins:300,400,500,600,700", "Roboto:300,400,500,600,700"]
            },
            active: function() {
                sessionStorage.fonts = true;
            }
        });
    </script>

    <!--end::Fonts -->


    <?php $this->registerLinkTag(['rel' => 'icon', 'type' => 'image/png', 'href' => Url::to(['/uinicon.png'])]); ?>
    <?php $this->head() ?>

</head>
<!-- begin::Body -->
<body class="kt-quick-panel--right kt-demo-panel--right kt-offcanvas-panel--right kt-header--fixed kt-header-mobile--fixed kt-subheader--fixed kt-subheader--enabled kt-subheader--solid kt-aside--enabled kt-aside--fixed kt-page--loading">

<?php $this->beginBody() ?>
<!-- begin:: Page -->
        <?=$content?>


<!-- end:: Page -->

<!-- begin::Global Config(global config for global JS sciprts) -->
<script>
    var KTAppOptions = {
        "colors": {
            "state": {
                "brand": "#5d78ff",
                "dark": "#282a3c",
                "light": "#ffffff",
                "primary": "#5867dd",
                "success": "#34bfa3",
                "info": "#36a3f7",
                "warning": "#ffb822",
                "danger": "#fd3995"
            },
            "base": {
                "label": ["#c5cbe3", "#a1a8c3", "#3d4465", "#3e4466"],
                "shape": ["#f0f3ff", "#d9dffa", "#afb4d4", "#646c9a"]
            }
        }
    };
</script>

<!-- end::Global Config -->

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

penjual/views/layouts/main-login.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use common\assets\metronic\MetronicLoginPageDemo6Asset;
use common\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;
use yii\helpers\Url;
use yii\widgets\Breadcrumbs;

MetronicLoginPageDemo6Asset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <!--begin::Fonts -->
    <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.16/webfont.js"></script>
    <script>
        WebFont.load({
            google: {
                "families": ["Poppins:300,400,500,600,700", "Roboto:300,400,500,600,700"]
            },
            active: function() {
                sessionStorage.fonts = true;
            }
        });
    </script>

    <!--end::Fonts -->
    <?php $this->registerLinkTag(['rel' => 'icon', 'type' => 'image/png', 'href' => Url::to(['/uinicon.png'])]); ?>


    <?php $this->head() ?>

</head>

<body class="kt-quick-panel--right kt-demo-panel--right kt-offcanvas-panel--right kt-header--fixed kt-header-mobile--fixed kt-subheader--fixed kt-subheader--enabled kt-subheader--solid kt-aside--enabled kt-aside--fixed kt-page--loading">

<?php $this->beginBody() ?>

<!-- begin:: Page -->
<div class="kt-grid kt-grid--ver kt-grid--root">
    <div class="kt-grid kt-grid--hor kt-grid--root  kt-login kt-login--v3 kt-login--signin" id="kt_login">
        <div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor" style="background-image: url(<?=Yii::getAlias('@web/media/bg/bg-3.jpg')?>);">
            <div class="kt-grid__item kt-grid__item--fluid kt-login__wrapper">
                <div class="kt-login__container">
                    <div class="kt-login__logo">
                        <a href="#">
                            <?=Html::img('@web/media/logos/logo-5.png')?>
                        </a>
                    </div>
                   <?=$content?>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- end:: Page -->

<!-- begin::Global Config(global config for global JS sciprts) -->
<script>
    var KTAppOptions = {
        "colors": {
            "state": {
                "brand": "#5d78ff",
                "dark": "#282a3c",
                "light": "#ffffff",
                "primary": "#5867dd",
                "success": "#34bfa3",
                "info": "#36a3f7",
                "warning": "#ffb822",
                "danger": "#fd3995"
            },
            "base": {
                "label": ["#c5cbe3", "#a1a8c3", "#3d4465", "#3e4466"],
                "shape": ["#f0f3ff", "#d9dffa", "#afb4d4", "#646c9a"]
            }
        }
    };
</script>

<!-- end::Global Config -->

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

penjual/views/layouts/main.php
<?php

/* @var $this \yii\web\View */

/* @var $content string */

use common\assets\metronic\MetronicDashboardDemo6Asset;
use yii\helpers\Html;

MetronicDashboardDemo6Asset::register($this);
$counterUp = <<<JS
 $('.counter').counterUp({
        delay: 10,
        time: 1000
    });
JS;
$this->registerJs($counterUp, \yii\web\View::POS_READY);
?>
<?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?php $this->registerCsrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?> - Devmall Booth</title>
        <!--begin::Fonts -->
        <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.16/webfont.js"></script>
        <script>
            WebFont.load({
                google: {
                    "families": ["Poppins:300,400,500,600,700", "Roboto:300,400,500,600,700"]
                },
                active: function () {
                    sessionStorage.fonts = true;
                }
            });
        </script>

        <!--end::Fonts -->

        <?php $this->head() ?>
    </head>
    <!-- begin::Body -->
    <body class="kt-quick-panel--right kt-demo-panel--right kt-offcanvas-panel--right kt-header--fixed kt-header-mobile--fixed kt-subheader--enabled kt-subheader--solid kt-aside--enabled kt-aside--fixed kt-aside--minimize kt-page--loading">
    <!-- begin:: Page -->

    <?php $this->beginBody() ?>

    <?= $this->render('mobile_header') ?>

    <div class="kt-grid kt-grid--hor kt-grid--root">
        <div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--ver kt-page">

            <?= $this->render('aside') ?>

            <div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor kt-wrapper" id="kt_wrapper">

                <?= $this->render('header') ?>
                <div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor">

                    <?= $this->render('subheader') ?>
                    <?= \dominus77\sweetalert2\Alert::widget(['useSessionFlash' => true]) ?>


                    <?= $this->render('content', ['content' => $content]) ?>
                </div>

                <?= $this->render('footer') ?>
            </div>
        </div>
    </div>


    <!-- end:: Page -->


    <!-- begin::Scrolltop -->
    <div id="kt_scrolltop" class="kt-scrolltop">
        <i class="fa fa-arrow-up"></i>
    </div>

    <!-- end::Scrolltop -->


    <!-- begin::Global Config(global config for global JS sciprts) -->
    <script>
        var KTAppOptions = {
            "colors": {
                "state": {
                    "brand": "#5d78ff",
                    "dark": "#282a3c",
                    "light": "#ffffff",
                    "primary": "#5867dd",
                    "success": "#34bfa3",
                    "info": "#36a3f7",
                    "warning": "#ffb822",
                    "danger": "#fd3995"
                },
                "base": {
                    "label": ["#c5cbe3", "#a1a8c3", "#3d4465", "#3e4466"],
                    "shape": ["#f0f3ff", "#d9dffa", "#afb4d4", "#646c9a"]
                }
            }
        };
    </script>


    <!-- end::Global Config -->
    <?php $this->endBody() ?>
    <?php
    yii\bootstrap4\Modal::begin([
        'title' => '<span id="modalHeaderTitle"></span>',
        'headerOptions' => ['id' => 'modalHeader'],
        'id' => 'modal',
        'size' => 'modal-lg',
        'clientOptions' => ['backdrop' => 'static', 'keyboard' => FALSE]


    ]);
    echo "<div id='modalContent'></div>";
    yii\bootstrap4\Modal::end();
    ?>
    </body>
    </html>
<?php $this->endPage() ?>

penjual/views/layouts/mobile_header.php
<?php

use yii\bootstrap4\Html;

?>

<!-- begin:: Header Mobile -->
<div id="kt_header_mobile" class="kt-header-mobile  kt-header-mobile--fixed ">
    <div class="kt-header-mobile__logo">
        <?= \yii\bootstrap4\Html::a(Html::img(Yii::getAlias('@web/media/logos/logo_sistem_uin.png'),['alt'=>'logo','width'=>200,'height'=>30]),['site/index']) ?>
    </div>
    <div class="kt-header-mobile__toolbar">
        <div class="kt-header-mobile__toolbar-toggler kt-header-mobile__toolbar-toggler--left" id="kt_aside_mobile_toggler"><span></span></div>
        <div class="kt-header-mobile__toolbar-toggler" id="kt_header_mobile_toggler"><span></span></div>
        <div class="kt-header-mobile__toolbar-topbar-toggler" id="kt_header_mobile_topbar_toggler"><i class="flaticon-more"></i></div>
    </div>
</div>

<!-- end:: Header Mobile -->

penjual/views/layouts/subheader.php
<?php

use common\widgets\Breadcrumbs;

?>
<!-- begin:: Subheader -->
<div class="kt-subheader   kt-grid__item" id="kt_subheader">
    <div class="kt-subheader__main">
        <h3 class="kt-subheader__title">
            <?=$this->title?> </h3>
        <span class="kt-subheader__separator kt-hidden"></span>

        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>

    </div>
</div>

<!-- end:: Subheader -->