common/models/Keranjang.php
<?php

namespace common\models;

use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "keranjang".
 *
 * @property int $id
 * @property int $id_user
 * @property int $id_produk
 * @property int $is_nego
 * @property int $id_harga_nego
 * @property int $is_diskon
 * @property int $created_at
 * @property int $updated_at
 *
 * @property Produk $produk
 * @property User $user
 * @property HargaNego $hargaNego
 * @property Diskon $diskon
 */
class Keranjang extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'keranjang';
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::class
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id_user', 'id_produk', 'created_at', 'updated_at'], 'integer'],
            [['id_produk'], 'exist', 'skipOnError' => true, 'targetClass' => Produk::className(), 'targetAttribute' => ['id_produk' => 'id']],
            [['id_user'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['id_user' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_user' => 'Id User',
            'id_produk' => 'Id Produk',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProduk()
    {
        return $this->hasOne(Produk::className(), ['id' => 'id_produk']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'id_user']);
    }

    public function getHargaNego()
    {
        return $this->hasOne(HargaNego::className(), ['id' => 'id_harga_nego']);
    }

    public function getDiskon()
    {
        return $this->hasOne(Diskon::className(), ['id_produk' => 'id_produk']);
    }
}

frontend/controllers/KeranjangController.php
<?php


namespace frontend\controllers;


use common\models\HargaNego;
use common\models\Keranjang;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\web\Controller;

class KeranjangController extends Controller
{


    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'tambah' => ['POST'],
                    'hapus' => ['POST'],
                ]
            ]
        ];
    }

    public function actionTambah()
    {

        $data = Yii::$app->request->post();
        $is_nego = filter_var($data['is_nego'], FILTER_VALIDATE_BOOLEAN);
        $is_diskon = filter_var($data['is_diskon'], FILTER_VALIDATE_BOOLEAN);

        $keranjang = new Keranjang();
        $keranjang->id_user = $data['user'];
        $keranjang->id_produk = $data['produk'];
        $keranjang->is_diskon = $is_diskon;
        $keranjang->is_nego = $is_nego;
        if ($is_nego) {
            $keranjang->id_harga_nego = HargaNego::findOne(['id_produk' => $data['produk'], 'id_user' => $data['user']]);
        }
        $keranjang->save(false);

        return $this->redirect(Yii::$app->request->referrer ?: $this->goBack());
    }

    public function actionHapus()
    {
        $data = Yii::$app->request->post();
        $keranjang = Keranjang::findOne(['id_produk' => $data['produk'], 'id_user' => $data['user']]);
        $keranjang->delete();

        return $this->redirect(Yii::$app->request->referrer ?: $this->goBack());

    }

    public function actionIndex()
    {
        $keranjang = \Yii::$app->user->identity->getKeranjangs();
        $keranjangCount = $keranjang->count();
        $keranjangDataProvider = new ActiveDataProvider(['query' => $keranjang]);
        $keranjangTotal = array_sum(array_values(ArrayHelper::map($keranjang->all(), 'harga', 'harga')));


        return $this->render('index', compact('keranjang', 'keranjangCount', 'keranjangDataProvider', 'keranjangTotal'));
    }
}

frontend/views/keranjang/index.php
<?php

use common\models\Produk;
use yii\bootstrap4\Html;
use yii\helpers\StringHelper;

/**
 * @var $this yii\web\View;
 * @var $keranjangDataProvider yii\data\ActiveDataProvider;
 * @var $keranjangCount int
 * @var $keranjangTotal int
 */

$this->title = 'Keranjang Belanjaan';
$this->params['breadcrumbs'][] = $this->title;


?>

<!--================================
         START DASHBOARD AREA
 =================================-->
<section class="cart_area section--padding2 bgcolor">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="product_archive added_to__cart">
                    <div class="title_area">
                        <div class="row">
                            <div class="col-md-5">
                                <h4>Produk</h4>
                            </div>
                            <div class="col-md-3">
                                <h4 class="add_info">Kategori</h4>
                            </div>
                            <div class="col-md-2">
                                <h4>Harga</h4>
                            </div>
                            <div class="col-md-2">
                                <h4>Hapus</h4>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <?php foreach ($keranjangDataProvider->models as /** @var $produk Produk */
                                       $produk): ?>
                            <div class="col-md-12">
                                <div class="single_product clearfix">
                                    <div class="col-lg-5 col-md-7 v_middle">
                                        <div class="product__description">
                                            <?= Html::img('@.penjual/upload/produk/' . $produk->galeriProduks[0]->nama_berkas, ['width' => '30%', 'height' => 120]) ?>
                                            <div class="short_desc">
                                                <a href="single-product.html">
                                                    <h4><?= $produk->nama ?></h4>
                                                </a>
                                                <?= StringHelper::truncateWords($produk->deskripsi, 20, '...', true) ?>
                                            </div>
                                        </div>
                                        <!-- end /.product__description -->
                                    </div>
                                    <!-- end /.col-md-5 -->

                                    <div class="col-lg-3 col-md-2 v_middle">
                                        <div class="product__additional_info">
                                            <ul>
                                                <?php foreach ($produk->kategoriProduk as $kategoriProduk): ?>
                                                    <li>
                                                        <?= $kategoriProduk->nama ?>
                                                    </li>
                                                <?php endforeach; ?>
                                            </ul>
                                        </div>
                                        <!-- end /.product__additional_info -->
                                    </div>
                                    <!-- end /.col-md-3 -->

                                    <div class="col-lg-4 col-md-3 v_middle">
                                        <div class="product__price_download">
                                            <div class="item_price v_middle">
                                                <span><?= Yii::$app->formatter->asCurrency($produk->harga) ?></span>
                                            </div>
                                            <div class="item_action v_middle">
                                                <?= Html::a('<span class="lnr lnr-trash"></span>', ['keranjang/hapus'], ['class' => 'remove_from_cart', 'data' => [
                                                    'method' => 'POST',
                                                    'params' => [
                                                        'produk' => $produk->id,
                                                        'user' => Yii::$app->user->identity->getId()
                                                    ]
                                                ]]) ?>
                                            </div>
                                            <!-- end /.item_action -->
                                        </div>
                                        <!-- end /.product__price_download -->
                                    </div>
                                    <!-- end /.col-md-4 -->
                                </div>
                                <!-- end /.single_product -->
                            </div>
                        <?php endforeach; ?>
                    </div>
                    <!-- end /.row -->

                    <div class="row">
                        <div class="col-md-6 offset-md-6">
                            <div class="cart_calculation">
                                <div class="cart--subtotal">
                                    <p>
                                        <span>Jumlah produk</span><?= $keranjangCount ?></p>
                                </div>
                                <div class="cart--total">
                                    <p>
                                        <span>Total</span><?= Yii::$app->formatter->asCurrency($keranjangTotal) ?></p>
                                </div>

                                <?php if (!($keranjangCount > 0)): ?>
                                    <?= Html::button('Lanjut ke Pembayaran', ['class' => 'btn btn--round btn--md btn--disabled checkout_link', 'disabled' => true]) ?>
                                <?php else: ?>
                                    <?= Html::a('Lanjut ke Pembayaran', ['pembayaran/checkout'], ['class' => 'btn btn--round btn--md checkout_link']) ?>
                                <?php endif; ?>
                            </div>
                        </div>
                        <!-- end .col-md-12 -->
                    </div>
                    <!-- end .row -->
                </div>
                <!-- end /.product_archive2 -->
            </div>
            <!-- end .col-md-12 -->
        </div>
        <!-- end .row -->

    </div>
    <!-- end .container -->
</section>
<!--================================
        END DASHBOARD AREA
=================================-->