penjual/controllers/ProdukController.php
<?php

namespace penjual\controllers;

use Carbon\Carbon;
use common\models\Booth;
use common\models\GaleriProduk;
use common\models\Kategori;
use common\models\Nego;
use common\models\Produk;
use penjual\models\ProdukSearch;
use Yii;
use yii\db\Exception;
use yii\filters\VerbFilter;
use yii\helpers\FileHelper;
use yii\web\Controller;
use yii\web\MethodNotAllowedHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\web\UploadedFile;


/**
 * ProdukController implements the CRUD actions for Produk model.
 */
class ProdukController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Produk models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ProdukSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Produk model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $gambar = $model->galeriProduks;
        return $this->render('view', [
            'model' => $model,
            'gambar' => $gambar
        ]);
    }

    /**
     * Finds the Produk model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Produk the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Produk::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /**
     * Creates a new Produk model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Produk();
        $negoModel = new Nego();
        $galeriModel = new GaleriProduk();
        $dataGaleri = null;
        /** @var $booth Booth */
        $booth = Yii::$app->user->identity->booth;
        if ($model->load(Yii::$app->request->post()) && $negoModel->load(Yii::$app->request->post()) && $galeriModel->load(Yii::$app->request->post())) {

            $manual = UploadedFile::getInstance($model, 'manual');
            $galeri = UploadedFile::getInstances($galeriModel, 'nama_berkas');
            $transaction = Yii::$app->db->beginTransaction();

            $model->id_booth = $booth->id;
            if (!empty($manual)) {
                $timestamp = Carbon::now()->timestamp;
                $filename = $timestamp . '-' . $manual->baseName . '.' . $manual->extension;
                $model->manual = $filename;
                $manual->saveAs(Yii::getAlias("@penjual/web/upload/produk/") . $filename);


            }
            if (!$model->save(false)) {
                throw new Exception('Gagal menyimpan produk');
            }
            if ($model->nego) {
                $nego = new Nego();
                $nego->setAttributes($negoModel->attributes);
                $nego->id_produk = $model->id;;
                $nego->save(false);
            }

            if (!empty($galeri)) {
                foreach ($galeri as $file) {
                    $timestamp = Carbon::now()->timestamp;
                    $filename = $timestamp . '-' . $file->baseName . '.' . $file->extension;
                    $galeri = new GaleriProduk();
                    $galeri->id_produk = $model->id;
                    $galeri->nama_berkas = $filename;
                    $galeri->jenis_berkas = $file->extension;
                    $galeri->save(false);
                    $file->saveAs(Yii::getAlias("@penjual/web/upload/produk/") . $filename);

                }
            }
            try {
                $transaction->commit();
            } catch (Exception $e) {
                $transaction->rollBack();
                throw $e;
            }


            Yii::$app->session->setFlash('success', 'Berhasil menambahkan Produk.');

            return $this->redirect(['view', 'id' => $model->id]);
        }
        return $this->render('create', [
            'model' => $model,
            'negoModel' => $negoModel,
            'galeriModel' => $galeriModel,
            'dataGaleri' => $dataGaleri

        ]);
    }

    /**
     * Updates an existing Produk model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = Produk::findOne($id);
        $negoModel = $model->nego0;
        if(empty($negoModel)){
            $negoModel = new Nego();
        }
        $galeriModel = new GaleriProduk();
        $booth = Yii::$app->user->identity->booth;

        $dataGaleri = GaleriProduk::find()->where(['id_produk' => $model->id])->all();

        if ($model->load(Yii::$app->request->post()) && $negoModel->load(Yii::$app->request->post()) && $galeriModel->load(Yii::$app->request->post())) {

            $manual = UploadedFile::getInstance($model, 'manual');
            $galeri = UploadedFile::getInstances($galeriModel, 'nama_berkas');
            $transaction = Yii::$app->db->beginTransaction();

            $model->id_booth = $booth->id;
            if (!empty($manual)) {
                $timestamp = Carbon::now()->timestamp;
                $filename = $timestamp . '-' . $manual->baseName . '.' . $manual->extension;
                $model->manual = $filename;
                $manual->saveAs(Yii::getAlias("@penjual/web/upload/produk/") . $filename);


            }
            if (!$model->update(false)) {
                throw new Exception('Gagal menyimpan produk');
            }
            if ($model->nego) {
                if($negoModel){
                    $negoModel->id_produk = $model->id;;
                    $negoModel->setAttributes($negoModel->attributes);
                    $negoModel->update(false);

                }

            }

            if (!empty($galeri)) {
                foreach ($galeri as $file) {
                    $timestamp = Carbon::now()->timestamp;
                    $filename = $timestamp . '-' . $file->baseName . '.' . $file->extension;
                    $galeri = new GaleriProduk();
                    $galeri->id_produk = $model->id;
                    $galeri->nama_berkas = $filename;
                    $galeri->jenis_berkas = $file->extension;
                    $galeri->save(false);
                    $file->saveAs(Yii::getAlias("@penjual/web/upload/produk/") . $filename);

                }
            }
            try {
                $transaction->commit();
                return $this->redirect(['produk/view', 'id' => $model->id]);
            } catch (Exception $e) {
                $transaction->rollBack();
                throw $e;
            }

        }
            return $this->render('update', [
                'model' => $model,
                'negoModel' => $negoModel,
                'galeriModel' => $galeriModel,
                'dataGaleri' => $dataGaleri

            ]);
        }


    /**
     * Deletes an existing Produk model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        Yii::$app->session->setFlash('success', 'Berhasil menghapus Produk.');

        return $this->redirect(['index']);
    }

    public function actionKategoriList($query)
    {
        $models = Kategori::find()->all();
        $items = [];

        foreach ($models as $model) {
            $items[] = ['name' => $model->nama];
        }

        Yii::$app->response->format = Response::FORMAT_JSON;

        return $items;

    }

    public function actionHapusManual($id)
    {
        if (Yii::$app->request->isPost) {

            $data = Yii::$app->request->post();

            $id = $data['id'];
            $produk = $this->findModel($id);
            $path = Yii::getAlias('@produkPath');
            $deleteDokumen = FileHelper::unlink($path . "/" . $produk->manual);
            if ($deleteDokumen) {
                $produk->manual = null;
                Yii::$app->session->setFlash('success', 'Berhasil menghapus dokumen led');
                return $this->redirect(['produk/update', 'id' => $id]);

            }
            Yii::$app->session->setFlash('success', 'Gagal menghapus dokumen led');
            return $this->redirect(['produk/update', 'id' => $id]);

        }

        return new MethodNotAllowedHttpException('Harus melalui prosedur penghapusan data.');
    }

    public function actionDownloadManual($id)
    {
        ini_set('max_execution_time', 5 * 60);
        $model = $this->findModel($id);
        $file = Yii::getAlias('@produkPath' . "/{$model->manual}");
        return Yii::$app->response->sendFile($file);
    }

    public function actionDownloadGaleri($id)
    {
        ini_set('max_execution_time', 5 * 60);
        $model = GaleriProduk::findOne($id);
        $file = Yii::getAlias('@produkPath' . "/{$model->nama_berkas}");
        return Yii::$app->response->sendFile($file);

    }

    public function actionHapusGaleri($id)
    {

penjual/views/produk/_form.php
<?php

use common\helpers\FileIconHelper;
use common\helpers\FileTypeHelper;
use common\models\constants\FileExtension;
use dosamigos\tinymce\TinyMce;
use kartik\file\FileInput;
use kartik\number\NumberControl;
use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;
use yii\bootstrap4\Modal;
use yii\helpers\FileHelper;


/* @var $this yii\web\View */
/* @var $model common\models\Produk */
/* @var $form ActiveForm; */
/* @var $galeriModel common\models\GaleriProduk */
/* @var $negoModel common\models\Nego */
/* @var $dataGaleri [] */


?>


    <div class="produk-form">

        <?php $form = ActiveForm::begin(['id' => 'produk-form']); ?>

        <?= $form->field($model, 'nama')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'kategori')->widget(
            \dosamigos\selectize\SelectizeTextInput::className(),
            [
                'loadUrl' => ['produk/kategori-list'],
                'options' => ['class' => 'form-control','required'=>true],
                'clientOptions' => [
                    'plugins' => ['remove_button'],
                    'valueField' => 'name',
                    'labelField' => 'name',
                    'searchField' => ['name'],
                ],
            ]
        )->hint('Use commas to separate tags') ?>
        <?= $form->field($model, 'deskripsi')->widget(TinyMce::class, []) ?>

        <?= $form->field($model, 'spesifikasi')->widget(TinyMce::class, []) ?>

        <?= $form->field($model, 'fitur')->widget(TinyMce::class, []) ?>

        <?= $form->field($model, 'harga')->widget(NumberControl::class, [
            'maskedInputOptions' => [
                'prefix' => 'Rp '
            ],

        ]) ?>
        <?= $form->field($model, 'nego')->checkbox() ?>

        <div class="nego d-none">
            <?= $form->field($negoModel, 'harga_satu')->widget(NumberControl::class, [
                'maskedInputOptions' => [
                    'prefix' => 'Rp '
                ]
            ]) ?>

            <?= $form->field($negoModel, 'harga_dua')->widget(NumberControl::class, [
                'maskedInputOptions' => [
                    'prefix' => 'Rp '
                ]
            ]) ?>

            <?= $form->field($negoModel, 'harga_tiga')->widget(NumberControl::class, [
                'maskedInputOptions' => [
                    'prefix' => 'Rp '
                ]
            ]) ?>
        </div>


        <?= $form->field($model, 'demo')->textInput() ?>



        <?php if (!$model->isNewRecord): ?>
            <div class="row">
                <div class="col-lg-12">
                    <h4>Manual</h4>
                    <table class="table">
                        <thead class="thead-dark">
                        <tr>
                            <th>Berkas</th>
                            <th>Aksi</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>
                                <div class="row">
                                    <div class="col-lg-12 text-center">
                                        <?php
                                        $extensions = FileHelper::getExtensionsByMimeType(FileHelper::getMimeType(Yii::getAlias('@penjual/web/upload/produk/' . $model->manual)))[0];
                                        echo FileIconHelper::getIconByExtension($extensions) ?>
                                    </div>

                                </div>
                                <div class="row">
                                    <div class="col-lg-12 text-center">
                                        <?= Html::encode($model->manual) ?>

                                    </div>
                                </div>
                            </td>
                            <td>
                                <div class="row pull-right">
                                    <div class="col-lg-12">
                                        <?php $type = FileTypeHelper::getType($extensions);
                                        if ($type === FileTypeHelper::TYPE_PDF):?>
                                            <?php Modal::begin([
                                                'title' => $model->manual,
                                                'toggleButton' => ['label' => '<i class="la la-eye"></i> &nbsp;Lihat', 'class' => 'btn btn-info btn-pill btn-elevate btn-elevate-air'],
                                                'size' => 'modal-lg',
                                                'clientOptions' => ['backdrop' => 'blur', 'keyboard' => true]
                                            ]);

                                            echo '<embed src="' . Yii::getAlias('@.produkPath') . '/' . $model->manual . '" type="application/pdf" height="100%" width="100%">
';
                                            ?>

                                            <?php Modal::end(); ?>
                                        <?php endif; ?>
                                        <?= Html::a('<i class ="la la-download"></i> Unduh', ['produk/download-manual', 'id' => $model->id], ['class' => 'btn btn-warning btn-pill btn-elevate btn-elevate-air']) ?>
                                        <?= Html::a('<i class ="la la-trash"></i> Hapus', ['produk/hapus-manual', 'id' => $model->id], ['class' => 'btn btn-danger btn-pill btn-elevate btn-elevate-air']) ?>
                                    </div>

                                </div>


                            </td>

                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        <?php else: ?>
            <?= $form->field($model, 'manual')->widget(FileInput::class, [
                'pluginOptions' => [
                    'theme' => 'explorer-fas',
                    'allowedFileExtensions' => FileExtension::DOKUMEN,
                    'showUpload' => false,
                    'previewFileType' => 'any',
                    'fileActionSettings' => [
                        'showZoom' => true,
                        'showRemove' => false,
                        'showUpload' => false,
                    ],
                ]
            ]) ?>
        <?php endif; ?>
        <?= $form->field($galeriModel, 'nama_berkas[]')->widget(FileInput::class, [
            'options' => [
                'multiple' => true
            ],
            'pluginOptions' => [
                'allowedFileExtensions' => FileExtension::FOTO,
                'showUpload' => false,
                'previewFileType' => 'image',
                'fileActionSettings' => [
                    'showZoom' => true,
                    'showRemove' => false,
                    'showUpload' => false,
                ],
            ]
        ])->label('Galeri Produk')->hint('Ukuran maksimal 5MB, jpeg/png') ?>
        <?php if (!empty($dataGaleri)) :
            ?>

            <div class="row">
                <div class="col-lg-12">
                    <h4>Galeri Produk</h4>
                    <table class="table">
                        <thead class="thead-dark">
                        <tr>
                            <th>Berkas</th>
                            <th>Aksi</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($dataGaleri as $item) : ?>
                            <tr>
                                <td>
                                    <?= Html::img(Yii::getAlias('@.produkPath/' . $item->nama_berkas), ['width' => '30%']);
                                    ?>
                                </td>
                                <td>
                                    <div class="row pull-right">
                                        <div class="col-lg-12">

                                            <?= Html::a('<i class ="la la-download"></i> Unduh', ['produk/download-galeri', 'id' => $item->id], ['class' => 'btn btn-warning btn-pill btn-elevate btn-elevate-air']) ?>
                                            <?= Html::a('<i class ="la la-trash"></i> Hapus', ['produk/hapus-galeri', 'id' => $item->id], ['class' => 'btn btn-danger btn-pill btn-elevate btn-elevate-air']) ?>
                                        </div>

                                    </div>


                                </td>

                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>

        <?php endif; ?>

        <div class="form-group">
            <?= Html::submitButton('<i class=\'la la-save\'></i> Simpan', ['class' => 'btn btn-pill btn-elevate btn-elevate-air btn-brand']) ?>
        </div>

        <?php ActiveForm::end(); ?>

    </div>

<?php $js = <<<JS
$(document).ready(function() {
   var checked = $('#produk-nego').prop('checked');
    if(checked){
       $('.nego').removeClass('d-none');
    }
    else{
        $('.nego').addClass('d-none');
    }
});
$('#produk-nego').on('change',function() {
    var checked = $('#produk-nego').prop('checked');
    if(checked){
       $('.nego').removeClass('d-none');
    }
    else{
        $('.nego').addClass('d-none');
    }
});
 $('form').on('beforeSubmit', function()
    {
        var form = $(this);
        //console.log('before submit');

        var submit = form.find(':submit');
        KTApp.block('.modal',{
            overlayColor: '#000000',
            type: 'v2',
            state: 'primary',
            message: 'Sedang Memproses...'
        });
        submit.html('<i class="flaticon2-refresh"></i> Sedang Memproses');
        submit.prop('disabled', true);

        KTApp.blockPage({
            overlayColor: '#000000',
            type: 'v2',
            state: 'primary',
            message: 'Sedang memproses...'
        });

    });

JS;

$this->registerJs($js);
?>

penjual/views/produk/_items.php
<?php
/**
 * @var $model common\models\Produk
 */

use yii\bootstrap4\Html; ?>

<div class="kt-pricing-1__visual">
    <div class="kt-pricing-1__hexagon1"></div>
    <div class="kt-pricing-1__hexagon2"></div>

    <span class="kt-pricing-1__icon kt-font-brand"><?= Html::img(Yii::getAlias('@.produkPath/' . $model->galeriProduks[0]->nama_berkas), ['width' => '80%', 'height' => 120]) ?></span>
</div>
<span class="kt-pricing-1__price"><?= \yii\helpers\StringHelper::mb_ucwords(Html::encode($model->nama)) ?></span>
<h2 class="kt-pricing-1__subtitle"><?= Yii::$app->formatter->asCurrency($model->harga) ?></h2>
<span class="kt-pricing-1__description">
													<?= \yii\helpers\StringHelper::truncate($model->deskripsi, '80', '...', 'UTF-8', true) ?>
												</span>
<div class="kt-pricing-1__btn">
    <?= Html::a('<i class="la la-eye"></i> Lihat', ['produk/view', 'id' => $model->id], ['class' => 'btn btn-brand btn-custom btn-pill btn-wide btn-uppercase btn-bolder btn-sm']) ?>
</div>

penjual/views/produk/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model penjual\models\ProdukSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="produk-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'id_booth') ?>

    <?= $form->field($model, 'nama') ?>

    <?= $form->field($model, 'deskripsi') ?>

    <?= $form->field($model, 'spesifikasi') ?>

    <?php // echo $form->field($model, 'fitur') ?>

    <?php // echo $form->field($model, 'harga') ?>

    <?php // echo $form->field($model, 'demo') ?>

    <?php // echo $form->field($model, 'manual') ?>

    <?php // echo $form->field($model, 'nego') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

penjual/views/produk/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Produk */
/* @var $galeriModel common\models\GaleriProduk */
/* @var $negoModel common\models\Nego */
/* @var $dataGaleri [] */

$this->title = 'Tambah Produk';
$this->params['breadcrumbs'][] = ['label' => 'Produk', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
    <div class="col-lg-12">

        <!--begin::Portlet-->
        <div class="kt-portlet">
            <div class="kt-portlet__head">
                <div class="kt-portlet__head-label">
                    <span class="kt-portlet__head-icon">
                        <i class="flaticon2-add-1"></i>
                    </span>
                    <h3 class="kt-portlet__head-title">
                        <?= Html::encode($this->title) ?>
                    </h3>
                </div>
            </div>
            <div class="kt-portlet__body">
                <div class="produk-create">

                    <?= $this->render('_form', [
                        'model' => $model,
                        'negoModel' => $negoModel,
                        'galeriModel' => $galeriModel,
                        'dataGaleri' => $dataGaleri


                    ]) ?>

                </div>
            </div>
        </div>
        <!--end::Portlet-->

    </div>
</div>

penjual/views/produk/index.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $searchModel penjual\models\ProdukSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
\common\assets\metronic\MetronicDashboardPricingAsset::register($this);
$colsCount = 3;

$this->title = 'Produk';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
    <div class="col-lg-12">

        <!--begin::Portlet-->
        <div class="kt-portlet">
            <div class="kt-portlet__head">
                <div class="kt-portlet__head-label">
                    <span class="kt-portlet__head-icon">
                        <i class="flaticon2-list-2"></i>
                    </span>
                    <h3 class="kt-portlet__head-title">
                        <?= Html::encode($this->title) ?>
                    </h3>
                </div>
                <div class="kt-portlet__head-toolbar">
                    <div class="kt-portlet__head-wrapper">
                        <div class="kt-portlet__head-actions">
                            <?= Html::a('<i class=flaticon2-add></i> Tambah Produk', ['create'], ['class' => 'btn btn-success btn-elevate btn-elevate-air']) ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="kt-portlet__body">
                <div class="kt-pricing-1">
                    <div class="kt-pricing-1__items">
                        <?= \yii\widgets\ListView::widget([
                            'dataProvider' => $dataProvider,
                            'itemView' => '_items',
                            'summary' => false,
                            'itemOptions' => [
                                'class' => 'kt-pricing-1__item col-lg-3'

                            ],
                            'beforeItem' => function ($model, $key, $index, $widget) use ($colsCount) {
                                if ($index % $colsCount === 0) {
                                    return "<div class='row'>";
                                }
                                return '';
                            },
                            'afterItem' => function ($model, $key, $index, $widget) use ($colsCount) {
                                $content = '';
                                if (($index > 0) && ($index % $colsCount === $colsCount - 1)) {
                                    $content .= "</div>";
                                }
                                return $content;
                            },
                        ]);
                        if ($dataProvider->count % $colsCount !== 0) {
                            echo "</div>";
                        } ?>
                        <!-- end /.row -->

                    </div>
                </div>
            </div>
        </div>
        <!--end::Portlet-->

    </div>
</div>

penjual/views/produk/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Produk */
/* @var $galeriModel common\models\GaleriProduk */
/* @var $negoModel common\models\Nego */
/* @var $dataGaleri [] */

$this->title = 'Ubah Produk: ' . $model->nama;
$this->params['breadcrumbs'][] = ['label' => 'Produk', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Ubah';
?>

<div class="row">
    <div class="col-lg-12">

        <!--begin::Portlet-->
        <div class="kt-portlet">
            <div class="kt-portlet__head">
                <div class="kt-portlet__head-label">
                    <span class="kt-portlet__head-icon">
                        <i class="flaticon2-edit"></i>
                    </span>
                    <h3 class="kt-portlet__head-title">
                        <?= Html::encode($this->title) ?>
                    </h3>
                </div>
            </div>
            <div class="kt-portlet__body">
                <div class="produk-update">

                    <?= $this->render('_form', [
                        'model' => $model,
                        'negoModel' => $negoModel,
                        'galeriModel' => $galeriModel,
                        'dataGaleri' => $dataGaleri
                    ]) ?>

                </div>
            </div>
        </div>
        <!--end::Portlet-->

    </div>
</div>